custom: ["https://www.paypal.com/us/fundraiser/charity/1710114", "https://smile.amazon.com/ref=smi_ext_ch_47-1318587_dl?_encoding=UTF8&ein=47-1318587&ref_=smi_chpf_redirect&ref_=smi_ext_ch_47-1318587_cl"]
