[book]
title = "FRC 167 Documentation"
authors = ["Iowa City Robotics", "Dominic Rutkowski"]
description = "Documentation for Iowa City Robotics (FRC Team 167)"
src = "src"
language = "en"

[output.html]
additional-css = ["theme/style.css"]
default-theme = "rust"
preferred-dark-theme = "navy"
mathjax-support = true
google-analytics = "UA-139208286-3"
git-repository-url = "https://github.com/icrobotics-team167/docs"
git-repository-icon = "fa-github"
