name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1.1.12
        with:
          mdbook-version: "0.4.3"

      - run: mdbook build

      - run: cp CNAME ./book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
